FROM php:8.1-apache

# Installeer de vereiste PHP-extensies (PDO en AMQP)
RUN apt-get update && apt-get install -y \
    librabbitmq-dev \
    && docker-php-ext-install sockets \
    && pecl install amqp || true \
    && docker-php-ext-enable sockets amqp \
    && docker-php-ext-install pdo pdo_mysql