services:
  wordpress:
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile-wordpress
    image: wordpress:latest
    ports:
      - "30011:80"
    volumes:
      - ./.docker/uploads:/var/www/html/wp-content/uploads
      - ./wp-content:/var/www/html/wp-content
      - ./rabbitmq:/var/www/html/rabbitmq
      - ./vendor:/var/www/html/vendor
    environment:
      - WORDPRESS_DB_HOST=${LOCAL_DB_HOST} # tijdelijk lokale MySQL container
      - WORDPRESS_DB_USER=${LOCAL_DB_USER}
      - WORDPRESS_DB_PASSWORD=${LOCAL_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${LOCAL_DB_NAME}
      - WORDPRESS_TABLEPREFIX=wp
      - WORDPRESS_DEBUG=1

  db:
    env_file: ./.env
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${LOCAL_DB_PASSWORD}
      - MYSQL_DATABASE=${LOCAL_DB_NAME}
    volumes:
      - ./.docker/mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=${LOCAL_DB_HOST}
      - PMA_USER=${LOCAL_DB_USER}
      - PMA_PASSWORD=${LOCAL_DB_PASSWORD}
      - PMA_ARBITRARY=1

  rabbitmq:
    image: rabbitmq:4-management
    container_name: some-rabbit
    restart: always
    environment:
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_HOST}
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}" # 15672:15672 RabbitMQ Management
      - "${RABBITMQ_AMQP_PORT}:${RABBITMQ_AMQP_PORT}" # "5672:5672" AMQP
    volumes:
      - /home/frontend/volumes/rabbitmq/data:/var/lib/rabbitmq

  python:
    env_file: ./.env
    image: python:3.9
    container_name: configure-service
    volumes:
      - ./configure.py:/usr/local/bin/configure.py
      - ./wait.sh:/usr/local/bin/wait.sh
    environment:
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    depends_on:
      - rabbitmq
    command:
      - "sh"
      - "-c"
      - "pip install pika && /usr/local/bin/wait.sh && python3 /usr/local/bin/configure.py"

  consumer-user:
    env_file: ./.env
    image: wordpress:latest
    build:
      context: .
      dockerfile: dockerfile-consumer
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./rabbitmq:/var/www/html/rabbitmq
      - ./vendor:/var/www/html/vendor
    environment:
      - WORDPRESS_DB_HOST=${LOCAL_DB_HOST}
      - WORDPRESS_DB_USER=${LOCAL_DB_USER}
      - WORDPRESS_DB_PASSWORD=${LOCAL_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${LOCAL_DB_NAME}
    command: php /var/www/html/rabbitmq/consumer.php
    depends_on:
      - db
      - rabbitmq
    restart: always

  heartbeat:
    env_file: ./.env
    image: python:3.9
    volumes:
      - ./heartbeat/heartbeat.py:/usr/local/bin/heartbeat.py
      - ./wait.sh:/usr/local/bin/wait.sh
    environment:
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
      - LOCAL_DB_NAME=${LOCAL_DB_NAME}
    depends_on:
      - rabbitmq
      - db
    command:
      - "sh"
      - "-c"
      - "pip install pika && /usr/local/bin/wait.sh && pip install mysql-connector-python && python3 /usr/local/bin/heartbeat.py"
