FROM php:8.1-cli

# Installer les extensions PHP nécessaires
RUN apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev \
    && docker-php-ext-install mysqli

WORKDIR /usr/src/app

COPY ./volumes/scripts/create_event_payments_table.php .

CMD ["php", "create_event_payments_table.php"]
