services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: some-rabbit
    restart: always
    environment:
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_ROOT_PASSWORD}
      RABBITMQ_DEFAULT_USER: attendify
      RABBITMQ_DEFAULT_VHOST: attendify
    ports:
      - "15672:15672" # RabbitMQ
      - "5672:5672"   #AMQP
    volumes:
      - ~/volumes/rabbitmq/data:/var/lib/rabbitmq