FROM php:8.1-apache

# Installeer de vereiste PHP-extensies (PDO en AMQP)
RUN apt-get update && apt-get install -y \
    librabbitmq-dev \
    && pecl install amqp \
    && docker-php-ext-enable amqp \
    && docker-php-ext-install pdo pdo_mysql

