services:
  consumer-payment:
    env_file: ./.env
    image: php:8.1-apache
    build:
      context: .
      dockerfile: dockerfile-consumer
    volumes:
      - ./volumes/rabbitmq:/var/www/html/rabbitmq
      - ./volumes/vendor:/var/www/html/vendor
    command: php /var/www/html/rabbitmq/InvoiceConsumer.php
    depends_on:
      - db
    restart: always
    networks:
      - attendify_net
      - frontend_net
  wordpress:
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile-wordpress
    image: wordpress:latest
    ports:
      - "${WORDPRESS_PORT}:80"
    volumes:
      - ./volumes/.docker/uploads:/var/www/html/wp-content/uploads
      - ./volumes/wp-content:/var/www/html/wp-content
      - ./volumes/rabbitmq:/var/www/html/rabbitmq
      - ./volumes/vendor:/var/www/html/vendor
      - ./volumes/scripts:/var/www/html/scripts
    environment:
      - WORDPRESS_DB_HOST=${LOCAL_DB_HOST}
      - WORDPRESS_DB_USER=${LOCAL_DB_USER}
      - WORDPRESS_DB_PASSWORD=${LOCAL_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${LOCAL_DB_NAME}
      - WORDPRESS_TABLEPREFIX=wp
      - WORDPRESS_DEBUG=0
    networks:
      - attendify_net
      - frontend_net

  db:
    env_file: ./.env
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${LOCAL_DB_PASSWORD}
      - MYSQL_DATABASE=${LOCAL_DB_NAME}
      - MYSQL_USER=${LOCAL_DB_USER}
      - MYSQL_PASSWORD=${LOCAL_DB_PASSWORD}
    volumes:
      - ./volumes/.docker/mysql-data:/var/lib/mysql
    networks:
      - frontend_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=${LOCAL_DB_HOST}
      - PMA_USER=${LOCAL_DB_USER}
      - PMA_PASSWORD=${LOCAL_DB_PASSWORD}
      - PMA_ARBITRARY=1
    networks:
      - frontend_net

  rabbitmq:
    image: rabbitmq:4-management
    container_name: some-rabbit
    restart: always
    environment:
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_HOST}
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "${RABBITMQ_AMQP_PORT}:${RABBITMQ_AMQP_PORT}"
    volumes:
      - /home/frontend/volumes/rabbitmq/data:/var/lib/rabbitmq
    profiles:
      - dev
    networks:
      - attendify_net
      - frontend_net

  python:
    env_file: ./.env
    image: python:3.9
    container_name: configure-service
    volumes:
      - ./volumes/configure.py:/usr/local/bin/configure.py
    environment:
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    depends_on:
      - rabbitmq
    command:
      - "sh"
      - "-c"
      - "pip install pika && python3 /usr/local/bin/configure.py"
    restart: on-failure
    profiles:
      - dev
    networks:
      - attendify_net
      - frontend_net

  consumer-user:
    env_file: ./.env
    image: php:8.1-apache
    build:
      context: .
      dockerfile: dockerfile-consumer
    volumes:
      - ./volumes/rabbitmq:/var/www/html/rabbitmq
      - ./volumes/vendor:/var/www/html/vendor
    environment:
      - LOCAL_DB_HOST=${LOCAL_DB_HOST}
      - LOCAL_DB_USER=${LOCAL_DB_USER}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
      - LOCAL_DB_NAME=${LOCAL_DB_NAME}
    command: php /var/www/html/rabbitmq/RabbitMQ_Consumer.php
    depends_on:
      - db
    restart: always
    networks:
      - attendify_net
      - frontend_net

  consumer-event:
    env_file: ./.env
    image: php:8.1-cli
    build:
      context: .
      dockerfile: dockerfile-consumer
    volumes:
      - ./volumes/rabbitmq:/var/www/html/rabbitmq
      - ./volumes/vendor:/var/www/html/vendor
    environment:
      - LOCAL_DB_HOST=${LOCAL_DB_HOST}
      - LOCAL_DB_USER=${LOCAL_DB_USER}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
      - LOCAL_DB_NAME=${LOCAL_DB_NAME}
    command: php /var/www/html/rabbitmq/UnifiedConsumerEventSession.php
    depends_on:
      - db
    restart: always
    networks:
      - attendify_net
      - frontend_net

  heartbeat:
    env_file: ./.env
    image: python:3.9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/heartbeat/heartbeat.py:/usr/local/bin/heartbeat.py
    environment:
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
      - LOCAL_DB_NAME=${LOCAL_DB_NAME}
    depends_on:
      - db
    command:
      - "sh"
      - "-c"
      - "pip install pika && pip install mysql-connector-python && python3 /usr/local/bin/heartbeat.py"
    restart: on-failure
    networks:
      - attendify_net
      - frontend_net

  consumer-company:
    env_file: ./.env
    image: php:8.1-cli
    build:
      context: .
      dockerfile: dockerfile-consumer
    volumes:
      - ./volumes/rabbitmq:/var/www/html/rabbitmq
      - ./volumes/vendor:/var/www/html/vendor
    environment:
      - LOCAL_DB_HOST=${LOCAL_DB_HOST}
      - LOCAL_DB_USER=${LOCAL_DB_USER}
      - LOCAL_DB_PASSWORD=${LOCAL_DB_PASSWORD}
      - LOCAL_DB_NAME=${LOCAL_DB_NAME}
    command: php /var/www/html/rabbitmq/CompanyConsumer.php
    depends_on:
      - db
    restart: always
    networks:
      - attendify_net
      - frontend_net
networks:
  attendify_net:
    driver: bridge
    name: attendify_net_dev
  frontend_net:
    driver: bridge
