name: WordPress CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - test
      - main
  pull_request:
    branches:
      - test
      - main

jobs:
  ci:
    name: Build and Test WordPress
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/test'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, curl
          tools: composer

      - name: Install dependencies
        run: |
          if [ -f composer.json ]; then
            composer install --no-dev --prefer-dist --no-progress --no-interaction
          fi

      - name: Lint PHP files
        run: find . -name "*.php" -print0 | xargs -0 -n1 php -l

      - name: Run PHPUnit tests
        run: |
          if [ -f vendor/bin/phpunit ]; then
            vendor/bin/phpunit
          else
            echo "PHPUnit not found, skipping tests."
          fi

  deploy-test:
    name: Deploy to Test Server
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/test'

    steps:
      - name: Deploy to test via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: ${{ secrets.TEST_SERVER_USER }}
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 60022
          script: |
            cd ~/attendify/test-environment/testing-Frontend

            if [ ! -d .git ]; then
              git clone -b test git@github.com:miladnnesim/attendify-frontend.git .
            else
              git remote set-url origin git@github.com:miladnnesim/attendify-frontend.git
              git fetch origin
              git checkout -B test origin/test
            fi

            docker compose down
            docker compose -f docker-compose.yaml up -d --build

  deploy-prod:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to production via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 60022
          script: |
            cd ~/attendify/attendify-frontend

            if [ ! -d .git ]; then
              git clone -b main git@github.com:miladnnesim/attendify-frontend.git .
            else
              git remote set-url origin git@github.com:miladnnesim/attendify-frontend.git
              git fetch origin
              git checkout -B main origin/main
            fi

            docker compose down
            docker compose -f docker-compose.yaml -f docker-compose.prod.yaml up -d --build
