name: WordPress CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Build and Test WordPress
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, curl
          tools: composer

      - name: Install dependencies
        run: |
          if [ -f composer.json ]; then
            composer install --no-dev --prefer-dist --no-progress --no-interaction
          fi

      - name: Lint PHP files
        run: find . -name "*.php" -print0 | xargs -0 -n1 php -l

      - name: Run PHPUnit tests
        run: |
          if [ -f vendor/bin/phpunit ]; then
            vendor/bin/phpunit
          else
            echo "PHPUnit not found, skipping tests."
          fi
