name: WordPress CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main
      - test
  pull_request:
    branches:
      - test
      - main

jobs:
  ci:
    name: Build and Test WordPress
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, curl
          tools: composer
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          if [ -f composer.json ]; then
            composer install --prefer-dist --no-progress --no-interaction
          fi

      - name: Run PHPUnit tests
        run: |
          ./vendor/bin/phpunit --configuration phpunit.xml --testdox

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/test'

    steps:
      - name: Deploy to test via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 60022
          script: |
            cd ~/attendify/test-environment/testing-Frontend/attendify-frontend
            git reset --hard origin/test
            git pull origin test
            docker compose down
            docker compose -f docker-compose.yaml -f docker-compose.test.yaml up -d --build

  deploy-prod:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to production via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 60022
          script: |
            cd ~/attendify/attendify-frontend
            git reset --hard origin/main
            git pull origin main
            docker compose down 
            docker compose -f docker-compose.yaml -f docker-compose.prod.yaml up -d --build
